# Generated by Django 4.1.7 on 2023-03-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferido', models.CharField(max_length=200)),
                ('periodo', models.CharField(max_length=255)),
            ],
        ),
    ]
