# Generated by Django 4.1.7 on 2023-04-02 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elevador', models.CharField(max_length=100)),
                ('turno', models.CharField(max_length=100)),
            ],
        ),
    ]
