# Generated by Django 4.1.7 on 2023-03-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_Atividade', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
            ],
        ),
    ]
