# Generated by Django 4.1.7 on 2023-03-16 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('quantidade_horas', models.FloatField(max_length=10000)),
                ('turno', models.CharField(max_length=255)),
                ('categoria', models.CharField(max_length=255)),
                ('valorTotal', models.FloatField(max_length=10000)),
                ('valorHora', models.FloatField(max_length=10000)),
            ],
        ),
    ]
