# Generated by Django 4.1.7 on 2023-03-12 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atividade1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='quantidade_horas',
            field=models.DecimalField(decimal_places=10, max_digits=10000),
        ),
    ]
