# Generated by Django 4.1.7 on 2023-03-12 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atividade1', '0002_alter_pagamento_quantidade_horas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='quantidade_horas',
            field=models.FloatField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='valorTotal',
            field=models.FloatField(max_length=10000),
        ),
    ]
